import { useMemo, useRef, useState } from "react";
import { compareTenants, parseTenant, type ComparisonItem, type Status, type Tenant } from "../src/comparison";

type View = "compare" | "review" | "summary";
type Decision = { choice: "source" | "target"; note: string; reviewed: boolean };
const tabs = ["All objects", "Applications", "Connections", "APIs", "Actions", "Organizations", "Rules"];
const glyphs: Record<string,string> = { swap:"⇄", check:"✓", clock:"◷", search:"⌕", upload:"↑", chevron:"›", close:"×", filter:"≡", download:"↓" };
function Icon({name}:{name:string}) { return <span aria-hidden="true">{glyphs[name]}</span>; }

export default function Home() {
  const [source, setSource] = useState<Tenant|null>(null); const [target, setTarget] = useState<Tenant|null>(null);
  const [view, setView] = useState<View>("compare"); const [activeTab, setActiveTab] = useState("All objects"); const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<ComparisonItem|null>(null); const [decisions, setDecisions] = useState<Record<string,Decision>>({});
  const [statusFilters, setStatusFilters] = useState<Set<Status>>(new Set(["changed","missing","target-only","match"])); const [showFilters, setShowFilters] = useState(false);
  const [error, setError] = useState(""); const fileRef = useRef<HTMLInputElement>(null);
  const items = useMemo(() => source && target ? compareTenants(source, target) : [], [source,target]);
  const reviewable = items.filter(item => item.status !== "match"); const reviewedCount = reviewable.filter(item => decisions[item.id]?.reviewed).length;
  const counts = (status: Status) => items.filter(item => item.status === status).length;
  const score = Math.max(0, 100 - items.reduce((sum,item) => sum + (item.severity === "High" ? 15 : item.severity === "Medium" ? 8 : item.severity === "Low" ? 3 : 0), 0));
  const filtered = items.filter(item => (activeTab === "All objects" || item.type === activeTab.replace(/s$/, "")) && statusFilters.has(item.status) && `${item.type} ${item.name}`.toLowerCase().includes(query.toLowerCase()) && (view !== "review" || (item.status !== "match" && !decisions[item.id]?.reviewed)));

  async function importFiles(files: FileList|null) {
    if (!files) return; setError("");
    if (files.length !== 2) { setError("Choose exactly two JSON files: source first, target second."); return; }
    try { const parsed = await Promise.all([...files].map(async file => parseTenant(JSON.parse(await file.text()), file.name))); setSource(parsed[0]); setTarget(parsed[1]); setDecisions({}); setSelected(null); setView("compare"); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "The exports could not be imported."); }
    finally { if (fileRef.current) fileRef.current.value = ""; }
  }
  function reset() { setSource(null); setTarget(null); setDecisions({}); setSelected(null); setQuery(""); setError(""); setView("compare"); }
  function saveDecision(id:string, choice:"source"|"target", note:string, reviewed:boolean) { setDecisions(current => ({...current,[id]:{choice,note,reviewed}})); }
  function downloadReport() {
    if (!source || !target) return;
    const payload = { generatedAt:new Date().toISOString(), source:{name:source.name,domain:source.domain}, target:{name:target.name,domain:target.domain}, readinessScore:score, decisions, comparison:items };
    const url = URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"})); const link=document.createElement("a"); link.href=url; link.download=`${source.name}-to-${target.name}-review.json`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(()=>URL.revokeObjectURL(url),1000);
  }

  return <main>
    <header className="topbar"><div className="brand"><div className="brandmark">TL</div><div><strong>Tenant Lens</strong><span>Auth0 migration workspace</span></div></div><nav aria-label="Primary">
      <button className={view==="compare"?"nav-active":""} onClick={()=>setView("compare")}><Icon name="swap"/> Compare</button>
      <button className={view==="review"?"nav-active":""} onClick={()=>setView("review")} disabled={!items.length}><Icon name="check"/> Review queue {items.length>0&&<b className="count">{reviewable.length-reviewedCount}</b>}</button>
      <button className={view==="summary"?"nav-active":""} onClick={()=>setView("summary")} disabled={!items.length}><Icon name="clock"/> Summary</button>
    </nav></header>
    <section className="workspace"><div className="title-row"><div><p className="eyebrow">{view === "review" ? "Review queue" : view === "summary" ? "Comparison summary" : "Comparison workspace"}</p><h1>{view === "review" ? "Resolve migration differences" : view === "summary" ? "Migration review summary" : "Tenant migration review"}</h1><p>{source&&target ? `${source.name} → ${target.name}` : "Import two tenant exports to compare configuration and surface migration risk."}</p></div><div className="title-actions">{source&&<button className="secondary" onClick={reset}>New comparison</button>}<button className="primary" onClick={()=>fileRef.current?.click()}><Icon name="upload"/> {source?"Replace exports":"Import tenant exports"}</button><input ref={fileRef} type="file" accept="application/json,.json" hidden multiple onChange={event=>void importFiles(event.target.files)}/></div></div>
      {error&&<div className="error-banner" role="alert">{error}</div>}
      {!source||!target ? <EmptyState onImport={()=>fileRef.current?.click()}/> : <>
        <div className="tenant-grid"><TenantCard kind="source" tenant={source}/><div className="transfer">⇄</div><TenantCard kind="target" tenant={target}/><article className="readiness"><div className="ring" style={{background:`conic-gradient(#3157d5 0 ${score}%,#edf0f4 ${score}%)`}}><strong>{score}</strong><span>/100</span></div><div><p className="eyebrow">Migration readiness</p><h3>{score>=90?"Ready":score>=70?"Needs attention":"High risk"}</h3><p>{counts("missing")+counts("changed")} source differences · {counts("target-only")} target-only</p></div></article></div>
        {view === "summary" ? <Summary items={items} decisions={decisions} score={score} onDownload={downloadReport}/> : <section className="comparison-panel"><div className="tabs" role="tablist">{tabs.map(tab=><button key={tab} className={activeTab===tab?"active":""} onClick={()=>setActiveTab(tab)}>{tab}{tab==="All objects"&&<span>{view==="review"?reviewable.length-reviewedCount:items.length}</span>}</button>)}</div><div className="toolbar"><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search objects…"/></label><button className="secondary" onClick={()=>setShowFilters(value=>!value)} aria-expanded={showFilters}><Icon name="filter"/> Filters <b className="filter-count">{statusFilters.size}</b></button><div className="legend"><span><i className="status-dot changed"/>Changed {counts("changed")}</span><span><i className="status-dot missing"/>Missing {counts("missing")}</span><span><i className="status-dot match"/>Match {counts("match")}</span></div></div>
          {showFilters&&<div className="filter-panel">{(["changed","missing","target-only","match"] as Status[]).map(status=><label key={status}><input type="checkbox" checked={statusFilters.has(status)} onChange={()=>setStatusFilters(current=>{const next=new Set(current); next.has(status)?next.delete(status):next.add(status); return next;})}/>{status === "target-only" ? "Target only" : status[0].toUpperCase()+status.slice(1)}</label>)}</div>}
          <ComparisonTable items={filtered} selected={selected} decisions={decisions} onSelect={setSelected}/>
        </section>}
      </>}
    </section>
    {selected&&<Inspector item={selected} decision={decisions[selected.id]} onClose={()=>setSelected(null)} onSave={(choice,note,reviewed)=>{saveDecision(selected.id,choice,note,reviewed); setSelected(null);}}/>}
  </main>;
}

function EmptyState({onImport}:{onImport:()=>void}) { return <section className="empty-state"><div className="empty-icon">⇄</div><h2>No tenant data loaded</h2><p>Select exactly two Auth0 JSON exports. Choose the source tenant first and the target tenant second. Files are processed locally in your browser and are not uploaded.</p><button className="primary" onClick={onImport}><Icon name="upload"/> Choose two JSON files</button><small>Supported collections: clients, connections, resource servers, Actions, organizations, and Rules.</small></section>; }
function TenantCard({kind,tenant}:{kind:"source"|"target";tenant:Tenant}) { return <article className={`tenant-card ${kind}`}><div className="tenant-label"><span className="dot"/> {kind.toUpperCase()} TENANT</div><div className="tenant-main"><div className="tenant-icon">{kind==="source"?"S":"T"}</div><div><h2>{tenant.name}</h2><p>{tenant.domain}</p></div></div><div className="tenant-meta"><span>{tenant.fileName}</span><span>{tenant.resources.length} objects</span></div></article>; }
function ComparisonTable({items,selected,decisions,onSelect}:{items:ComparisonItem[];selected:ComparisonItem|null;decisions:Record<string,Decision>;onSelect:(item:ComparisonItem)=>void}) { return <div className="table-wrap">{items.length ? <table><thead><tr><th>Object</th><th>Source</th><th>Target</th><th>Status</th><th>Impact</th><th>Review</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>onSelect(item)} className={selected?.id===item.id?"selected":""}><td><b className={`object-icon ${item.type.toLowerCase()}`}>{item.type[0]}</b><div><strong>{item.name}</strong><small>{item.type}</small></div></td><td>{item.source}</td><td className={item.status==="missing"?"muted":""}>{item.target}</td><td><span className={`status ${item.status}`}><i/>{item.status==="target-only"?"Target only":item.status[0].toUpperCase()+item.status.slice(1)}</span></td><td><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></td><td>{decisions[item.id]?.reviewed?<span className="reviewed">✓ Reviewed</span>:"—"}</td><td><Icon name="chevron"/></td></tr>)}</tbody></table> : <div className="empty">No objects match the current view.</div>}</div>; }
function Inspector({item,decision,onClose,onSave}:{item:ComparisonItem;decision?:Decision;onClose:()=>void;onSave:(choice:"source"|"target",note:string,reviewed:boolean)=>void}) { const [choice,setChoice]=useState<"source"|"target">(decision?.choice??"source"); const [note,setNote]=useState(decision?.note??""); return <><div className="scrim" onClick={onClose}/><aside className="drawer" aria-label="Difference inspector"><div className="drawer-head"><div><p className="eyebrow">{item.type}</p><h2>{item.name}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close inspector"><Icon name="close"/></button></div><div className="drawer-body"><div className={`notice ${item.severity.toLowerCase()}`}><strong>{item.severity==="None"?"Configuration matches":`${item.severity} impact difference`}</strong><p>{item.detail}</p></div><h3>Configuration diff</h3><div className="diff"><div><span>Source</span><code>{item.source}</code></div><div><span>Target</span><code>{item.target}</code></div></div>{item.status!=="match"&&<><h3>Review decision</h3><div className="decision"><button className={choice==="target"?"recommended":""} onClick={()=>setChoice("target")}>Accept target</button><button className={choice==="source"?"recommended":""} onClick={()=>setChoice("source")}>Migrate source</button></div><label className="note-label">Reviewer note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add context for the migration team…"/></label></>}</div><div className="drawer-footer"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(choice,note,item.status!=="match")}>{item.status==="match"?"Close":"Save and mark reviewed"}</button></div></aside></>; }
function Summary({items,decisions,score,onDownload}:{items:ComparisonItem[];decisions:Record<string,Decision>;score:number;onDownload:()=>void}) { const differences=items.filter(i=>i.status!=="match"); const reviewed=differences.filter(i=>decisions[i.id]?.reviewed).length; return <section className="summary-grid"><article><p className="eyebrow">Readiness score</p><strong>{score}/100</strong><span>Calculated from impact-weighted differences.</span></article><article><p className="eyebrow">Review progress</p><strong>{reviewed}/{differences.length}</strong><span>Differences reviewed and assigned a decision.</span></article><article><p className="eyebrow">Configuration</p><strong>{items.length}</strong><span>Total normalized objects compared.</span></article><div className="summary-action"><div><h2>Export migration report</h2><p>Download the comparison, readiness score, reviewer decisions, and notes as JSON.</p></div><button className="primary" onClick={onDownload}><Icon name="download"/> Download report</button></div></section>; }
