"use client";
import { useMemo, useRef, useState } from "react";

type Status = "changed" | "missing" | "match" | "target-only";
type Item = { id:number; type:string; name:string; source:string; target:string; status:Status; severity:"High"|"Medium"|"Low"|"None"; detail:string };
const items:Item[] = [
  {id:1,type:"Application",name:"Customer Portal",source:"SPA · RS256",target:"SPA · RS256",status:"changed",severity:"High",detail:"Allowed callback URLs differ. The target is missing the production callback and includes a localhost URL."},
  {id:2,type:"Connection",name:"Username-Password-Authentication",source:"5 settings",target:"5 settings",status:"match",severity:"None",detail:"Configuration, password policy, and enabled clients match."},
  {id:3,type:"Action",name:"Add roles to token",source:"Deployed · Node 18",target:"Not found",status:"missing",severity:"High",detail:"This post-login Action is not present in the target. Tokens will not include namespaced roles after cutover."},
  {id:4,type:"API",name:"Orders API",source:"8 permissions",target:"7 permissions",status:"changed",severity:"Medium",detail:"The target is missing the orders:refund permission."},
  {id:5,type:"Organization",name:"Northwind",source:"3 connections",target:"3 connections",status:"changed",severity:"Medium",detail:"Branding colors and the login prompt differ between tenants."},
  {id:6,type:"Rule",name:"Legacy email allowlist",source:"Enabled",target:"Not found",status:"missing",severity:"Low",detail:"Legacy Rule exists only in source. Consider migrating this logic to an Action rather than copying it."},
  {id:7,type:"Application",name:"Support Console",source:"Regular web app",target:"Regular web app",status:"match",severity:"None",detail:"Application type, grants, URLs, and connection assignments match."},
  {id:8,type:"Connection",name:"google-oauth2",source:"Enabled for 4 clients",target:"Enabled for 5 clients",status:"target-only",severity:"Low",detail:"The target enables Google login for one additional application: Marketing Preview."},
];
const tabs=["All objects","Applications","Connections","APIs","Actions","Organizations"];
const glyphs:Record<string,string>={swap:"⇄",check:"✓",clock:"◷",gear:"⚙",search:"⌕",upload:"↑",dots:"•••",chevron:"›",close:"×",filter:"≡"};
function Icon({name}:{name:string}){return <span aria-hidden="true">{glyphs[name]}</span>}

export default function Home(){
 const [activeTab,setActiveTab]=useState("All objects"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Item|null>(items[0]); const [loaded,setLoaded]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const filtered=useMemo(()=>items.filter(item=>(activeTab==="All objects"||item.type===activeTab.replace(/s$/,""))&&`${item.type} ${item.name}`.toLowerCase().includes(query.toLowerCase())),[activeTab,query]);
 return <main>
  <header className="topbar"><div className="brand"><div className="brandmark">TL</div><div><strong>Tenant Lens</strong><span>Auth0 migration workspace</span></div></div><nav aria-label="Primary"><button className="nav-active"><Icon name="swap"/> Compare</button><button><Icon name="check"/> Review queue <b className="count">6</b></button><button><Icon name="clock"/> Runs</button></nav><div className="top-actions"><button className="icon-button" aria-label="Settings"><Icon name="gear"/></button><div className="avatar">BR</div></div></header>
  <section className="workspace"><div className="title-row"><div><p className="eyebrow">Comparison workspace</p><h1>Tenant migration review</h1><p>Compare configuration, surface risk, and build a clean migration plan.</p></div><div className="title-actions"><button className="secondary" onClick={()=>setLoaded(false)}>New comparison</button><button className="primary" onClick={()=>fileRef.current?.click()}><Icon name="upload"/> Import tenant exports</button><input ref={fileRef} type="file" accept=".json" hidden multiple onChange={()=>setLoaded(true)}/></div></div>
   <div className="tenant-grid"><TenantCard kind="source" letter="S" name="acme-production" date="Aug 20, 2026" objects="48 objects"/><div className="transfer">⇄</div><TenantCard kind="target" letter="T" name="acme-staging" date="Aug 21, 2026" objects="43 objects"/><article className="readiness"><div className="ring"><strong>72</strong><span>/100</span></div><div><p className="eyebrow">Migration readiness</p><h3>Needs attention</h3><p>3 blockers · 5 warnings</p></div><button aria-label="View readiness"><Icon name="chevron"/></button></article></div>
   {loaded&&<div className="toast"><Icon name="check"/> Tenant export queued for comparison.</div>}
   <section className="comparison-panel"><div className="tabs" role="tablist">{tabs.map(tab=><button key={tab} className={activeTab===tab?"active":""} onClick={()=>setActiveTab(tab)}>{tab}{tab==="All objects"&&<span>48</span>}</button>)}</div><div className="toolbar"><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search objects…"/></label><button className="secondary"><Icon name="filter"/> Filters <b className="filter-count">2</b></button><div className="legend"><span><i className="status-dot changed"/>Changed 5</span><span><i className="status-dot missing"/>Missing 2</span><span><i className="status-dot match"/>Match 34</span></div></div>
    <div className="table-wrap"><table><thead><tr><th>Object</th><th>Source</th><th>Target</th><th>Status</th><th>Impact</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={item.id} onClick={()=>setSelected(item)} className={selected?.id===item.id?"selected":""}><td><b className={`object-icon ${item.type.toLowerCase()}`}>{item.type[0]}</b><div><strong>{item.name}</strong><small>{item.type}</small></div></td><td>{item.source}</td><td className={item.status==="missing"?"muted":""}>{item.target}</td><td><span className={`status ${item.status}`}><i/>{item.status==="target-only"?"Target only":item.status[0].toUpperCase()+item.status.slice(1)}</span></td><td><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></td><td><Icon name="chevron"/></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No objects match your search.</div>}</div>
   </section>
  </section>
  {selected&&<><div className="scrim" onClick={()=>setSelected(null)}/><aside className="drawer" aria-label="Difference inspector"><div className="drawer-head"><div><p className="eyebrow">{selected.type}</p><h2>{selected.name}</h2></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close inspector"><Icon name="close"/></button></div><div className="drawer-body"><div className={`notice ${selected.severity.toLowerCase()}`}><strong>{selected.severity==="None"?"Configuration matches":`${selected.severity} impact difference`}</strong><p>{selected.detail}</p></div><h3>Configuration diff</h3><div className="diff"><div><span>Source</span><code>{selected.source}</code></div><div><span>Target</span><code>{selected.target}</code></div></div><h3>Review decision</h3><div className="decision"><button>Accept target</button><button className="recommended">Migrate source</button></div><label className="note-label">Reviewer note<textarea placeholder="Add context for the migration team…"/></label></div><div className="drawer-footer"><button className="secondary" onClick={()=>setSelected(null)}>Close</button><button className="primary" onClick={()=>setSelected(null)}>Mark reviewed</button></div></aside></>}
 </main>
}
function TenantCard({kind,letter,name,date,objects}:{kind:string;letter:string;name:string;date:string;objects:string}){return <article className={`tenant-card ${kind}`}><div className="tenant-label"><span className="dot"/> {kind.toUpperCase()} TENANT</div><div className="tenant-main"><div className="tenant-icon">{letter}</div><div><h2>{name}</h2><p>us.auth0.com</p></div><button className="icon-button" aria-label={`${kind} menu`}><Icon name="dots"/></button></div><div className="tenant-meta"><span>Exported {date}</span><span>{objects}</span></div></article>}
